export const state = {
  lossHistory: [],
  gradHistory: [],
  allPieces: [],
  selectedPieces: [],
  muralTileSize: 16,
  muralMode: 'wallpaper',
  kaleidoRunning: false,
  kaleidoTimer: null,
  TRANSITION_MS: 3500,
  KALEIDO_FLIP_MS: 3500,
  muralTileRotation: true,
  muralPaused: false,
  layoutSeed: 0,
  layoutTimer: null,
  rotationTimer: null,
  // Game of Life
  gol: {
    grid: null,
    cols: 0,
    rows: 0,
    tileA: null,
    tileB: null,
    tileIdxA: 0,
    tileIdxB: 0,
    generation: 0,
    tickTimer: null,
    resetTimer: null,
    running: false,
  },
};
